fails:IO#close does not raise anything when self was already closed
fails:IO#close does nothing if already closed
